//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanKhau.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitizenDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CitizenDetail()
        {
            this.HouseholdBooks = new HashSet<HouseholdBook>();
            this.TemporaryRequests = new HashSet<TemporaryRequest>();
            this.HouseholdBooks1 = new HashSet<HouseholdBook>();
        }
    
        public int DetailId { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Address { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string CCCDId { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string Gender { get; set; }
        public string Name { get; set; }
        public string CCCDProvideAddress { get; set; }
        public System.DateTime CCCDProvideDate { get; set; }
        public string CCCDProvideUrgent { get; set; }
        public string Phone { get; set; }
        public string ContactEmail { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseholdBook> HouseholdBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemporaryRequest> TemporaryRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseholdBook> HouseholdBooks1 { get; set; }
    }
}
