//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanKhau.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseHoldMember
    {
        public int BookId { get; set; }
        public int CitizenId { get; set; }
    }
}
